name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Configure Git
        run: |
          git config --global user.email "kkmbal@gmail.com"
          git config --global user.name "lucirr"

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: ./build

          #      - name: Deploy to GitHub Pages
          #        env:
          #          GIT_USER: ${{ secrets.GIT_USER }}
          #          USE_SSH: false                        
          #          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} 
          #        run: npm run deploy      
